### ISSUE TITLE
[grid.walker] rename `add`

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-xt-grid#1]
_From @ftalbrecht on September 8, 2015 13:53_

Turns out calling this method `add` was a terrible choice. There are matrix-based operators in dune-gdt which derive from grid walker. There, `add` should clearly add two matrix-based operators. There might be other places where this naming is not appropriate.
The method in question registers functors with the grid walker for local application. I would have liked to call it `register`, which is of course not possible. But something along those lines would be nice.

Any ideas?

_Copied from original issue: wwu-numerik/dune-stuff#73_

**Comment by renemilk** [comment]
Maybe STL container like?

**Comment by renemilk** [comment]
[Thesaurus for register](http://www.thesaurus.com/browse/register?s=t)
[Thesaurus for add](http://www.thesaurus.com/browse/add?s=t)
So 'append' is imo fine, but I also really like 'affix' :wink:

**Comment by ftalbrecht** [comment]
`append` sounds good to me.
