### ISSUE TITLE
Virtual destructor for BoundaryType/BoundaryInfo?

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt-grid#10]
In commit 9b89d704af7eb610727a75cfde58c3e9aaf48e52 I silenced some warnings about BoundaryInfo/BoundaryType not having a virtual destructor. The non-virtual destructor can lead to memory leaks when deleting a derived class through the base type pointer. But adding a virtual destructor would make the BoundaryInfo class non-literal, which means it cannot be used as a constexpr variable. I do not think we will manually delete a BoundaryType/BoundaryInfo-derived through its base type pointer very often, so we could just leave the warning silenced and ignore it.

**Comment by ftalbrecht** [comment]
Mhm, do we need to be able to use these as consexpr? If not, I would add the dtor. Btw, was there a reason you did not use https://github.com/dune-community/dune-xt-common/blob/master/dune/xt/common/enable_warnings.hh and `disable_warnings.hh`?

**Comment by tobiasleibner** [comment]
It is used as constexpr variables at the moment, e.g. in ``boundaryinfo/allneumann.hh``. I did not use ``disable_warnings.hh`` because I thought we might want to get warnings other than `-Wnon-virtual-dtor` from these classes.

**Comment by renemilk** [comment]
Having (and using) the boundary types as constexpr is a nice optimization opportunity for the compiler imo. I vote keeping as is.

**Comment by ftalbrecht** [comment]
Ok, I agree. Maybe you could add a small comment in code documenting that we want warnings disabled to use this as constexpr?

**Comment by tobiasleibner** [comment]
Added the comment in 1f56bda80db6dc8f83da5cd2bb0815ddba38f436.
