### ISSUE TITLE
Add tests for currently untested code

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-grid#11]
**Moved from https://github.com/wwu-numerik/dune-stuff/issues/69**

Non-exhaustive list of code that should have at least rudimentary test coverage. As in does it compile in the usual use-case. 
## Grid
- [ ] entity.hh
- [ ] layers.hh
- [ ] search.hh (check complexity guarantees?)
- [ ] StructuredGridFactory

**Comment by renemilk** [comment]
https://codecov.io/gh/dune-community/dune-xt-grid/tree/master/dune/xt/grid

**Comment by tobiasleibner** [comment]
Moved to dune-xt.
