### ISSUE TITLE
Stop using external ALUGrid in favor of dune-alugrid?

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-xt-grid#2]
_From @renemilk on December 15, 2015 12:3_

I see no reason not to, besides transition is work. On the plus side It'll avoid link errors like https://travis-ci.org/wwu-numerik/dune-stuff/jobs/96946956#L4946 and be one less external lib to build.

_Copied from original issue: wwu-numerik/dune-stuff#95_

**Comment by renemilk** [comment]
_From @ftalbrecht on December 15, 2015 21:35_

I agree mostly! However, dune-alugrid behaves differently from alugrid. Using the same ctors yields other grids, for instance. So I am pro transitioning but would like to have some time to make sure we can keep all the functionality we require. Feel free to assign this to me.

**Comment by renemilk** [comment]
There's a compelling reason not to wait with this though: https://gitlab.dune-project.org/core/dune-grid/merge_requests/1
the support is already removed from dune-grid.

**Comment by renemilk** [comment]
This is closesly related to https://github.com/dune-community/dune-gdt/issues/79

**Comment by ftalbrecht** [comment]
Should be done by now...
