### ISSUE TITLE
Investigate entity search improvements

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt-grid#20]
Timo pointed me to the Bounding box tree implementation in DuMux, which should be faster when repeatedly searching for few coordinates.
Furthermore, currently we are searching for a entity for one coordinate at a time, then the next coordinate and so on. Wouldn't it be faster to do a single grid walk and test all coordinates at each entity (maybe removing the already matched coordinates).
I will do some performance measurements.

**Comment by renemilk** [comment]
TBH I've always been too lazy to a proper complexity analysis of the diff strategies, so I guess my answer would be "maybe". 
Either way it's _very_ dependent on your grid setup.

**Comment by tobiasleibner** [comment]
Closing this as I do not intend to work on this soon.
