### ISSUE TITLE
intersection range generator broken for wrapped subdomain grid part

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-grid#26]
The intersections (of custom type) of `SubdomainGridPart` are available via `part.ibegin(entity)`, as well as via `intersections(part, entity)`; both work as expected. When wrapped by `Fem::GridPart2GridView`, however, the latter triggers an assertion in alugrid, while the former still works.

**Comment by ftalbrecht** [comment]
This is a show stopper for #25.

**Comment by ftalbrecht** [comment]
In addition, the intersections of `SubdomainBoundaryGridPart` behave wrong when wrapped as a grid view (as in: not reporting the fake subdomain boundary correctly); both when accessed via `ibegin` or `intersections()`. This is most likely because some other intersection iterator is used, for instance the one of the underlying grid part...

**Comment by ftalbrecht** [comment]
The same holds for the `SubdomainCouplingGridPart`, when wrapped as a grid view...

**Comment by renemilk** [comment]
While the Subdomain* classes are now 'real' GridViews a/the intersection problem remains. It's only hidden now by using a custom iterator range object that does the right thing :tm: 
It's unclear to me why that works, but it does. We can keep this open as a reminder to some interested party to investigate this, but I for one won't. I'm also fine with closing as "works for me" :wink:
