### ISSUE TITLE
Introduction of dynamic grid views

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-grid#29]
As just decided, we want to provide a dynamic interface for grid views and grid parts, which deduces all relevant information from the given entity type. Its purpose is to provide:

* an entity iterator
* an intersetion iterator
* an index set

We thus need several dynamic interfaces and corresponding wrappers aounr existing views, parts, intersections, ...
Regarding the naming I would propose to just append `Interface`, e.g.,

* `GridViewInterface`
* `IntersectionInterface`
* `IntersectionIteratorInterface`
* `IndexSetInterface`

DUNE itself never/rarely uses the `Interface` postfix and by using it we do not need to come up with a good name describing something that already has a name...

In a first step, these interfaces only need to provide access to everything we require in the `dune-xt-` modules as well as `dune-gdt`.

The plan is currently leave the entities unchanged/unwrapped, but instead of using the grid as template argument we use the entities. This will allow us to use other non-standard entities later on...

**Comment by renemilk** [comment]
Referencing #31

**Comment by tobiasleibner** [comment]
We decided not to do this atm. We can reopen this in dune-xt if we want this at some point.
