### ISSUE TITLE
timeout not respected

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-grid#30]
`dd_glued_3d` times out after 300s...

**Comment by renemilk** [comment]
Did you check the actual cmake test command that cmake runs?

**Comment by ftalbrecht** [comment]
```bash
make VERBOSE=1 test
Running tests...
/usr/bin/ctest --force-new-ctest-process
...
```

**Comment by tobiasleibner** [comment]
Not sure if this is still an issue, we can reopen in dune-xt if that is the case.
