### ISSUE TITLE
[grid.fakeentity] is needed by dune-pymor

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-xt-grid#6]
_From @ftalbrecht on April 18, 2015 9:47_

For one of the examples.

_Copied from original issue: wwu-numerik/dune-stuff#47_

**Comment by renemilk** [comment]
Did you create this issue so we won't remove the fake entity again?

**Comment by renemilk** [comment]
_From @ftalbrecht on July 29, 2015 6:34_

Probably? :) I guess we should decide whether this stays here or is moved to dune-pymor...

**Comment by renemilk** [comment]
I can't think of a reason to keep it here then.

**Comment by renemilk** [comment]
_From @ftalbrecht on July 29, 2015 8:44_

Me neither, I guess. Though one could use it to enable tests of functions without requiring a grid, or such things. But I do not see an immediate need for this...

**Comment by ftalbrecht** [comment]
This does not apply to dune-xt-grid anymore.
