### ISSUE TITLE
periodic grid view should handle adaptive host views

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-grid#84]
This is currently a show stopper for adaptive grid refinement in the context of FV methods in dune-gdt. In a first step we could just add a means to completely recreate the periodic view after grid adaptation. Not sure yet what the obstacles will be there...

**Comment by tobiasleibner** [comment]
I am using the ``PeriodicGridView`` with adaptive grids already. Just call ``update`` after grid adaption. Even if it is called update, it just completely recreates all necessary maps. An actual update of the changed parts only would be nice, but I am not sure how to implement that. 
``PeriodicGridView`` together with an adaptive grid works fine as long as there is no adaptivity (or only symmetric adaptivity at both sides) of the periodic boundary. Adaptivity at the boundary usually results in nonconforming intersections along the periodic boundary which we can't handle yet. To change that, we would have to tell the grid to adapt conformingly across the periodic boundary, which probably is hard to do.

**Comment by renefritze** [comment]
Not sure what you're referring to with 'adaptive host views'. AFAIK the grid interface actually says loadbalance/adaption may invalidate views or at least all iterators.

**Comment by ftalbrecht** [comment]
> I am using the `PeriodicGridView` with adaptive grids already. Just call `update` after grid adaption. Even if it is called update, it just completely recreates all necessary maps.

I should have probably checked before opening an issue :) Great news!
